import type { AppStateComposition } from "./stateBindingTypes";

export function createUiStateBindings(appState: AppStateComposition) {
  const {
    sidebarWidth,
    setSidebarWidth,
    sidebarCollapsed,
    setSidebarCollapsed,
    serverPanelHeight,
    setServerPanelHeight,
    messagePaneHeight,
    setMessagePaneHeight,
    fontFamily,
    setFontFamily,
    fontSize,
    setFontSize,
    language,
    setLanguage,
    resolvedLanguage,
    exportFormatTemplate,
    setExportFormatTemplate,
    startSidebarResize,
    startServerPanelResize
  } = appState.layout;
  const { openPreferences, openPreferencesSection } = appState.preferences;
  const {
    serverContextMenu,
    setServerContextMenu,
    topicContextMenu,
    setTopicContextMenu,
    isTopicSortMenuOpen,
    setIsTopicSortMenuOpen,
    pendingTopicAction,
    setPendingTopicAction,
    topicActionConfirmText,
    setTopicActionConfirmText,
    draggingServerId,
    setDraggingServerId,
    serverDropTarget,
    setServerDropTarget,
    draggingFavoriteTopic,
    setDraggingFavoriteTopic,
    favoriteDropTarget,
    setFavoriteDropTarget,
    closeServerContextMenu,
    closeTopicContextMenu
  } = appState.sidebarInteraction;
  const {
    splitPane,
    setSplitPane,
    splitDropSide,
    setSplitDropSide,
    splitPrimaryPercent,
    activeWorkspacePane,
    setActiveWorkspacePane,
    activeDragPayload,
    setActiveDragPayload,
    startWorkspaceSplitResize
  } = appState.workspacePane;

  return {
    activeDragPayload,
    activeWorkspacePane,
    closeServerContextMenu,
    closeTopicContextMenu,
    draggingFavoriteTopic,
    draggingServerId,
    exportFormatTemplate,
    favoriteDropTarget,
    fontFamily,
    fontSize,
    isTopicSortMenuOpen,
    language,
    messagePaneHeight,
    openPreferences,
    openPreferencesSection,
    pendingTopicAction,
    resolvedLanguage,
    serverContextMenu,
    serverDropTarget,
    serverPanelHeight,
    setActiveDragPayload,
    setActiveWorkspacePane,
    setDraggingFavoriteTopic,
    setDraggingServerId,
    setExportFormatTemplate,
    setFavoriteDropTarget,
    setFontFamily,
    setFontSize,
    setIsTopicSortMenuOpen,
    setLanguage,
    setMessagePaneHeight,
    setPendingTopicAction,
    setServerContextMenu,
    setServerDropTarget,
    setServerPanelHeight,
    setSidebarCollapsed,
    setSidebarWidth,
    setSplitDropSide,
    setSplitPane,
    setTopicActionConfirmText,
    setTopicContextMenu,
    sidebarCollapsed,
    sidebarWidth,
    splitDropSide,
    splitPane,
    splitPrimaryPercent,
    startServerPanelResize,
    startSidebarResize,
    startWorkspaceSplitResize,
    topicActionConfirmText,
    topicContextMenu
  };
}
