import { useAppStateComposition } from "../state/useAppStateComposition";

export function useWorkspaceControllerStateBindings() {
  const appState = useAppStateComposition();
  const {
    servers,
    setServers,
    connectedServerIds,
    setConnectedServerIds,
    failedServerIds,
    setFailedServerIds,
    setHealthFailuresByServer,
    openClusterIds,
    setOpenClusterIds,
    selectedServerId,
    setSelectedServerId
  } = appState.serverCluster;
  const { openNewServerForm, openEditServerForm } = appState.serverForms;
  const { openTopicCreateForm, closeTopicCreateForm } = appState.topicCreateForms;
  const resourceState = appState.resources;
  const {
    viewByServer,
    setViewByServer,
    topicViewByServer,
    setTopicViewByServer,
    selectedTopicByServer,
    setSelectedTopicByServer,
    openedTopicTabsByServer,
    setOpenedTopicTabsByServer
  } = resourceState.navigation;
  const {
    topicsByServer,
    setTopicsByServer,
    topicGridSortingByServer,
    setTopicGridSortingByServer,
    favoriteTopicsByServer,
    setFavoriteTopicsByServer,
    topicDetailByServer,
    setTopicDetailByServer,
    topicDetailCacheByServer,
    setTopicDetailCacheByServer
  } = resourceState.topics;
  const {
    brokersByServer,
    setBrokersByServer
  } = resourceState.brokers;
  const {
    groupsByServer,
    setGroupsByServer,
    selectedGroupByServer,
    setSelectedGroupByServer,
    groupLagByServer,
    setGroupLagByServer
  } = resourceState.consumerGroups;
  const {
    consumeDefaultsByServer,
    setConsumeDefaultsByServer,
    manualAvroSchemasByServer,
    setManualAvroSchemasByServer,
    preferencesLoaded,
    setPreferencesLoaded
  } = resourceState.preferences;
  const {
    streamingTopicsByServer,
    setStreamingTopicsByServer
  } = resourceState.streaming;
  const {
    consumeStatesByServer,
    setConsumeStatesByServer,
    splitConsumeStatesByServer,
    setSplitConsumeStatesByServer,
    getDefaultConsumeState,
    setConsumeStates,
    mergeConsumeState,
    moveConsumeStateBetweenPanes,
    clearConsumeStateForPane,
    clearConsumeStatesForPane,
    updateConsumeStateFor
  } = appState.consumeState;
  const {
    getProduceDraft,
    updateProduceDraftFor,
    resetProduceDrafts
  } = appState.produceDrafts;
  const {
    getMessageTarget,
    setStartedConsumer,
    getStopConsumerId,
    clearStoppedConsumer,
    clearMessageTarget,
    retargetLiveTopic
  } = appState.liveConsumeRouting;
  const {
    setStatus,
    toast,
    setToast,
    paneToast,
    setPaneToast,
    loading,
    setLoading,
    activeConsumeTaskKeys,
    setActiveConsumeTaskKeys,
    setConnectionError
  } = appState.feedback;
  const {
    runTask,
    runPaneTask,
    runWorkspaceTask,
    showPaneToast
  } = appState.workspaceTasks;
  const {
    sidebarWidth,
    setSidebarWidth,
    sidebarCollapsed,
    setSidebarCollapsed,
    serverPanelHeight,
    setServerPanelHeight,
    messagePaneHeight,
    setMessagePaneHeight,
    fontFamily,
    setFontFamily,
    fontSize,
    setFontSize,
    language,
    setLanguage,
    resolvedLanguage,
    exportFormatTemplate,
    setExportFormatTemplate,
    startSidebarResize,
    startServerPanelResize
  } = appState.layout;
  const {
    openPreferences,
    openPreferencesSection
  } = appState.preferences;
  const {
    serverContextMenu,
    setServerContextMenu,
    topicContextMenu,
    setTopicContextMenu,
    isTopicSortMenuOpen,
    setIsTopicSortMenuOpen,
    pendingTopicAction,
    setPendingTopicAction,
    topicActionConfirmText,
    setTopicActionConfirmText,
    draggingServerId,
    setDraggingServerId,
    serverDropTarget,
    setServerDropTarget,
    draggingFavoriteTopic,
    setDraggingFavoriteTopic,
    favoriteDropTarget,
    setFavoriteDropTarget,
    closeServerContextMenu,
    closeTopicContextMenu
  } = appState.sidebarInteraction;
  const {
    splitPane,
    setSplitPane,
    splitDropSide,
    setSplitDropSide,
    splitPrimaryPercent,
    activeWorkspacePane,
    setActiveWorkspacePane,
    activeDragPayload,
    setActiveDragPayload,
    startWorkspaceSplitResize
  } = appState.workspacePane;

  return {
    activeConsumeTaskKeys,
    activeDragPayload,
    activeWorkspacePane,
    brokersByServer,
    clearConsumeStateForPane,
    clearConsumeStatesForPane,
    clearMessageTarget,
    clearStoppedConsumer,
    closeServerContextMenu,
    closeTopicContextMenu,
    closeTopicCreateForm,
    connectedServerIds,
    consumeDefaultsByServer,
    consumeStatesByServer,
    draggingFavoriteTopic,
    draggingServerId,
    exportFormatTemplate,
    failedServerIds,
    favoriteDropTarget,
    favoriteTopicsByServer,
    fontFamily,
    fontSize,
    getDefaultConsumeState,
    getMessageTarget,
    getProduceDraft,
    getStopConsumerId,
    groupLagByServer,
    groupsByServer,
    isTopicSortMenuOpen,
    language,
    loading,
    manualAvroSchemasByServer,
    mergeConsumeState,
    messagePaneHeight,
    moveConsumeStateBetweenPanes,
    openClusterIds,
    openEditServerForm,
    openNewServerForm,
    openPreferences,
    openPreferencesSection,
    openTopicCreateForm,
    openedTopicTabsByServer,
    paneToast,
    pendingTopicAction,
    preferencesLoaded,
    resetProduceDrafts,
    resolvedLanguage,
    retargetLiveTopic,
    runPaneTask,
    runTask,
    runWorkspaceTask,
    selectedGroupByServer,
    selectedServerId,
    selectedTopicByServer,
    serverContextMenu,
    serverDropTarget,
    serverPanelHeight,
    servers,
    setActiveConsumeTaskKeys,
    setActiveDragPayload,
    setActiveWorkspacePane,
    setBrokersByServer,
    setConnectedServerIds,
    setConnectionError,
    setConsumeDefaultsByServer,
    setConsumeStates,
    setConsumeStatesByServer,
    setDraggingFavoriteTopic,
    setDraggingServerId,
    setExportFormatTemplate,
    setFailedServerIds,
    setFavoriteDropTarget,
    setFavoriteTopicsByServer,
    setFontFamily,
    setFontSize,
    setGroupLagByServer,
    setGroupsByServer,
    setHealthFailuresByServer,
    setIsTopicSortMenuOpen,
    setLanguage,
    setLoading,
    setManualAvroSchemasByServer,
    setMessagePaneHeight,
    setOpenClusterIds,
    setOpenedTopicTabsByServer,
    setPaneToast,
    setPendingTopicAction,
    setPreferencesLoaded,
    setSelectedGroupByServer,
    setSelectedServerId,
    setSelectedTopicByServer,
    setServerContextMenu,
    setServerDropTarget,
    setServerPanelHeight,
    setServers,
    setSidebarCollapsed,
    setSidebarWidth,
    setSplitConsumeStatesByServer,
    setSplitDropSide,
    setSplitPane,
    setStartedConsumer,
    setStatus,
    setStreamingTopicsByServer,
    setToast,
    setTopicActionConfirmText,
    setTopicContextMenu,
    setTopicDetailByServer,
    setTopicDetailCacheByServer,
    setTopicGridSortingByServer,
    setTopicsByServer,
    setTopicViewByServer,
    setViewByServer,
    showPaneToast,
    sidebarCollapsed,
    sidebarWidth,
    splitConsumeStatesByServer,
    splitDropSide,
    splitPane,
    splitPrimaryPercent,
    startServerPanelResize,
    startSidebarResize,
    startWorkspaceSplitResize,
    streamingTopicsByServer,
    toast,
    topicActionConfirmText,
    topicContextMenu,
    topicDetailByServer,
    topicDetailCacheByServer,
    topicGridSortingByServer,
    topicsByServer,
    topicViewByServer,
    updateConsumeStateFor,
    updateProduceDraftFor,
    viewByServer
  };
}
