import { createRoot } from "react-dom/client";
import { App } from "./App";
import "./styles/fonts.css";
import "./styles/tokens.css";
import "./styles/themes/dark.css";
import "./styles.css";
import "./styles/surfaces.css";
import "./styles/workspace.css";
import "./styles/workspace-tabs.css";
import "./styles/consume-toolbar.css";
import "./styles/consume-status.css";
import "./styles/consume-grid.css";
import "./styles/message-inspector.css";
import "./styles/produce.css";
import "./styles/quick-search.css";
import "./styles/sidebar.css";
import "./styles/modals.css";
import "./styles/topic-list.css";
import "./styles/topic-overview.css";
import "./styles/topic-settings.css";
import "./styles/topic-actions.css";
import "./styles/consumer-groups.css";
import "./styles/brokers.css";
import "./styles/preferences.css";
import "./styles/controls.css";
import "./styles/tables.css";
import "./styles/toast.css";

createRoot(document.getElementById("root")!).render(<App />);
